## Lists, Dictionaries and Sets in Python

## Part 1

### Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [2]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]


List can also be created by using list() function. 

In [3]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]


Adding to an existing list

### Question 1

Add 10 to list l1 given above.

[ **Hint: ** Use **append** ]

In [11]:
l1.append(10)

Removing from an existing list

### Question 2

Remove 10 from l1.

[ **Hint:** Use **remove**]

In [13]:
l1.remove(10)

Joining 2 lists

### Question 3

[ **Hint: ** Use **+** operator or **extend**]

In [25]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [15]:
l1+l2
print(l1+l2)

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]


Number List

### Question 4

Find Range and Mean of l3.

l3 = [2,4,6,8]

[ **Hint: ** Use **len(),sum(), min(), max()** functions ]
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [111]:
import numpy as np
I3 = [2,4,6,8]


In [112]:
print(np.max(I3))
print(np.mean(I3))


8
5.0


Count the occurances of an element in a given list.

### Question 5
Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.

[ **Hint: ** Use ** + operator to add multiple elements in the array and count() function to print the occurences**]

In [113]:
I3=I3+[0,1,3,3,5,5,7,9]
print(I3)
I3.count(5)



[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]


2

Sorting and Reversing a list

### Question 6
sort and print l3 in ascending and descending order sequentially (given above)

**(Hint: Use .sort() function)**

In [114]:
print(np.sort(I3))


[0 1 2 3 3 4 5 5 6 7 8 9]


In [115]:
I3.sort(reverse=True)
I3

[9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]

### Functions

**Example:**

**def** function_name(args)**:**
    
    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [129]:
def sum_3(x,y,z):
    return(x+y+z)
result = sum_3(3,5,4)
print(result)

12


### Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2


### Question 8

Write the same above **sum_3** function using lambda.

In [137]:
new= lambda x, y, z, a : x + y+z+a
print(new(3,5,5,5))


18


# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [18]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [197]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [20]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2L, 4L)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [138]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function



In [246]:
new = [[9,8,7],[6,5,4],[3,2,1]]
newmat = np.matrix(new)
newmat

matrix([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [163]:
newmat.T

matrix([[9, 6, 3],
        [8, 5, 2],
        [7, 4, 1]])

### Question 4
Add + 1 to all the elements in the given matrix.

In [165]:
newmat+1

matrix([[10,  9,  8],
        [ 7,  6,  5],
        [ 4,  3,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [177]:
nd6 = [[ 1, 4, 9, 121, 144, 169],[ 16, 25, 36, 196, 225, 256],[ 49,64, 81, 289, 324, 361]]
np.matrix(nd6)

matrix([[  1,   4,   9, 121, 144, 169],
        [ 16,  25,  36, 196, 225, 256],
        [ 49,  64,  81, 289, 324, 361]])

In [180]:
np.mean(nd6)

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [199]:
new=np.dot(l1,l2)
new


70

# Pandas

We have seen Numpy in the last section. It is good at performing math operation on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](http://pandas.pydata.org/pandas-docs/version/0.23/dsintro.html)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [183]:
import numpy as np
import pandas as pd

In [188]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

[**Hint:** Use **.Series**]

In [185]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [190]:
new = pd.Series(d1)
new

a    1
b    2
c    3
dtype: int64

You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


[ **Hint: ** Use **np.dot()** ]

In [194]:
newseries= np.dot(series1,new)
newseries

14

## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column. 

In [200]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

### Question 3

Select second row in the above dataframe df1.



In [215]:
df1.loc[2]

a    3
b    5
c    8
Name: 2, dtype: int64

### Question 4

Select column c in second row of df1.

[ **Hint: ** For using labels use **df.loc[row, column]**. For using numeric indexed use **df.iloc[]**. For using mixture of numeric indexes and labels use **df.ix[row, column]** ]



In [216]:
df1.iloc[2,2]

8

## Using Dataframes on a dataset

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors 

In [220]:
## Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']


Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


[ **Hint: ** Use **type()** and **df.shape** ]

In [244]:
print(type(mtcars))
print(mtcars.shape)

<class 'pandas.core.frame.DataFrame'>
(32, 12)


### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

[**Hint:** Use **.head()** and **.tail()**]

In [228]:
mtcars.head(10)
mtcars.tail(10)

name   mpg  cyl   disp   hp  drat     wt   qsec  \
name                                                                            
AMC Javelin            AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   
Camaro Z28              Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   
Pontiac Firebird  Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   
Fiat X1-9                Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   
Porsche 914-2        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   
Lotus Europa          Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   
Ford Pantera L      Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   
Ferrari Dino          Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   
Maserati Bora        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   
Volvo 142E              Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   

                  vs  am  gear  carb  
name                                  
AMC Javelin        0   0     3     2  
Camaro Z28         0   0     3     4  
Pontiac Firebird   0   0     3     2  
Fiat X1-9          1   1     4     1  
Porsche 914-2      0   1     5     2  
Lotus Europa       1   1     5     2  
Ford Pantera L     0   1     5     4  
Ferrari Dino       0   1     5     6  
Maserati Bora      0   1     5     8  
Volvo 142E         1   1     4     2

In [241]:
mtcars.tail(10)


name   mpg  cyl   disp   hp  drat     wt   qsec  \
name                                                                            
AMC Javelin            AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   
Camaro Z28              Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   
Pontiac Firebird  Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   
Fiat X1-9                Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   
Porsche 914-2        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   
Lotus Europa          Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   
Ford Pantera L      Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   
Ferrari Dino          Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   
Maserati Bora        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   
Volvo 142E              Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   

                  vs  am  gear  carb  
name                                  
AMC Javelin        0   0     3     2  
Camaro Z28         0   0     3     4  
Pontiac Firebird   0   0     3     2  
Fiat X1-9          1   1     4     1  
Porsche 914-2      0   1     5     2  
Lotus Europa       1   1     5     2  
Ford Pantera L     0   1     5     4  
Ferrari Dino       0   1     5     6  
Maserati Bora      0   1     5     8  
Volvo 142E         1   1     4     2

### Question 7

Print all the column labels in the given dataset - mtcars.

[ **Hint: ** Use **df.columns** ]

In [237]:
mtcars.columns.values

array(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'], dtype=object)

### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

**Hint: **  
mtcars.ix[:,:] gives all rows and columns in the dataset.

In [240]:
mtcars.ix[:6,:3]

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


name   mpg  cyl
name                                           
Mazda RX4                  Mazda RX4  21.0    6
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6
Datsun 710                Datsun 710  22.8    4
Hornet 4 Drive        Hornet 4 Drive  21.4    6
Hornet Sportabout  Hornet Sportabout  18.7    8
Valiant                      Valiant  18.1    6